spring.application.name=captchasolver

ftp.host=172.17.60.142
ftp.port=21
ftp.username=ib_automation_alpha
ftp.password=ib@alpha
ftp.base-dir=/indiabulls/ib-automation/backoffice-input
csv.download.dir=C:\\Users\\gobind.barick\\Downloads