spring.application.name=captchasolver

ftp.host=192.168.53.134
ftp.port=2221
ftp.username=android
ftp.password=android
ftp.base-dir=/JAD
csv.download.dir=C:\\Users\\gobind.barick\\Downloads

login.url=https://www.connect2nsccl.com/auth/#/login
login.username=gobind
login.password=Dhani@123456
login.membercode=08756

scheduler.fixedRate=1800000


tesseract.datapath=C:\\Users\\gobind.barick\\AppData\\Local\\Programs\\Tesseract-OCR\\tessdata

email.host=imap.gmail.com
email.user=gobind.barick@indiabulls.com
email.password=fkolsfimzanoexce
email.sender.filter=CONNECT2NSCCL@nse.co.in
